import { nanoid } from 'nanoid';
import type { Meeting, MeetingStatus, CreateMeetingRequest, LobsterDialogueTurn, MeetingSummaryPayload } from '../realtime/types.js';

// In-memory store until @clawlive/db Drizzle schema is implemented
const meetings = new Map<string, Meeting>();

// Transcript storage: meetingId -> segments
const transcripts = new Map<string, Array<{ speakerId: string; speakerName?: string; text: string; timestamp: number }>>();

// Lobster dialogue storage: meetingId -> dialogue turns
const dialogues = new Map<string, LobsterDialogueTurn[]>();

// Registered lobster metadata: meetingId -> lobster info
const lobsters = new Map<string, Array<{ lobsterId: string; skillName: string; skillDescription: string; collaborationMode: string; ownerUserId: string }>>();

// Meeting summary: meetingId -> summary (generated by host lobster)
const summaries = new Map<string, MeetingSummaryPayload>();

const VALID_TRANSITIONS: Record<MeetingStatus, readonly MeetingStatus[]> = {
  lobby: ['active'],
  active: ['ended'],
  ended: [],
};

function canTransition(from: MeetingStatus, to: MeetingStatus): boolean {
  return VALID_TRANSITIONS[from].includes(to);
}

export function createMeeting(req: CreateMeetingRequest): Meeting {
  const meeting: Meeting = {
    id: nanoid(),
    title: req.title,
    description: req.description ?? '',
    status: 'lobby',
    createdAt: Date.now(),
    startedAt: null,
    endedAt: null,
  };
  meetings.set(meeting.id, meeting);
  transcripts.set(meeting.id, []);
  dialogues.set(meeting.id, []);
  lobsters.set(meeting.id, []);
  return meeting;
}

export function getMeeting(id: string, opts?: { includeArchived?: boolean }): Meeting | null {
  const m = meetings.get(id);
  if (!m) return null;
  // includeArchived: when false (default) and meeting status === 'ended', return null
  if (!opts?.includeArchived && m.status === 'ended') return null;
  return m;
}

export function listMeetings(): readonly Meeting[] {
  return Array.from(meetings.values()).sort((a, b) => b.createdAt - a.createdAt);
}

export function updateMeetingStatus(id: string, status: MeetingStatus): Meeting {
  const meeting = meetings.get(id);
  if (!meeting) {
    throw new MeetingNotFoundError(id);
  }
  if (!canTransition(meeting.status, status)) {
    throw new InvalidTransitionError(meeting.status, status);
  }

  const updated: Meeting = {
    ...meeting,
    status,
    startedAt: status === 'active' ? Date.now() : meeting.startedAt,
    endedAt: status === 'ended' ? Date.now() : meeting.endedAt,
  };
  meetings.set(id, updated);
  return updated;
}

export function startMeeting(id: string): Meeting {
  return updateMeetingStatus(id, 'active');
}

export function endMeeting(id: string): Meeting {
  return updateMeetingStatus(id, 'ended');
}

export function appendTranscript(
  meetingId: string,
  segment: { speakerId: string; speakerName?: string; text: string; timestamp: number },
): void {
  const segments = transcripts.get(meetingId);
  if (segments) {
    segments.push(segment);
  }
}

export function getTranscript(
  meetingId: string,
): readonly { speakerId: string; speakerName?: string; text: string; timestamp: number }[] {
  return transcripts.get(meetingId) ?? [];
}

// ── Lobster dialogue storage ──

export function appendDialogue(
  meetingId: string,
  turn: LobsterDialogueTurn,
): void {
  const turns = dialogues.get(meetingId);
  if (turns) {
    turns.push(turn);
  }
}

export function getDialogues(
  meetingId: string,
): readonly LobsterDialogueTurn[] {
  return dialogues.get(meetingId) ?? [];
}

// ── Lobster registration storage ──

export function registerLobster(
  meetingId: string,
  info: { lobsterId: string; skillName: string; skillDescription: string; collaborationMode: string; ownerUserId: string },
): void {
  const list = lobsters.get(meetingId);
  if (list) {
    // 避免重复注册
    if (!list.some((l) => l.lobsterId === info.lobsterId)) {
      list.push(info);
    }
  }
}

export function getLobsters(
  meetingId: string,
): readonly { lobsterId: string; skillName: string; skillDescription: string; collaborationMode: string; ownerUserId: string }[] {
  return lobsters.get(meetingId) ?? [];
}

// ── Meeting summary (generated by host lobster) ──

export function saveSummary(meetingId: string, payload: MeetingSummaryPayload): void {
  summaries.set(meetingId, payload);
}

export function getSummary(meetingId: string): MeetingSummaryPayload | null {
  return summaries.get(meetingId) ?? null;
}

export class MeetingNotFoundError extends Error {
  constructor(id: string) {
    super(`Meeting not found: ${id}`);
    this.name = 'MeetingNotFoundError';
  }
}

export class InvalidTransitionError extends Error {
  constructor(from: MeetingStatus, to: MeetingStatus) {
    super(`Invalid meeting status transition: ${from} -> ${to}`);
    this.name = 'InvalidTransitionError';
  }
}


/** Archive a meeting (soft-delete: status -> ended). */
export function archiveMeeting(id: string): boolean {
  const m = meetings.get(id);
  if (!m) return false;
  m.status = 'ended';
  m.endedAt = Date.now();
  return true;
}

// trigger A1+A2+A3 verify @ 20260428T063957Z

// regression test multi-forge refactor @ 20260428T071209Z

// regression 20260428T080143Z
